{include file="html/header"}
<div class="comm-actions">
	<a href="<?php echo module('cms')->getUrl('index/restadd'); ?>">添加餐厅</a>
	<a href="<?php echo module('cms')->getUrl('index/restset'); ?>">指定今日餐厅</a>
	<a href="<?php echo module('cms')->getUrl('index/menuadd'); ?>">添加菜单</a>
</div> 
<div class="add-user">
<form action="<?php echo module('cms')->getUrl('admin/menuadd'); ?>" method="post">
	<div><label>所属餐厅：</label><select type="text" name="menurid">
		<option value='' selected><span>请选择</span></option>
		<?php echo module('admin')->getRestList('select'); ?>
	</select>   </div>
	<div><label>套餐名称：</label><input type="text" name="menuname" />  </div>
	<div><label>价格：</label><input type="text" name="menuprice" />   </div>
	<div><label>状态：</label><select type="text" name="menulock">  
		<option value="0" selected><span>正常</span></option>
		<option value="1"><span>锁定</span></option>
	</select>  <br /> </div>
	<div class="sub-action">
	<input type="reset" value="重置" />
	<input type="submit" value="添加" />
	</div>
</form>
<a class="goback" href="<?php echo module('cms')->getUrl('index/menuadmin'); ?>">返回菜单管理</a>
</div>

{include file="html/footer"}