{include file="html/header"}
<div class="comm-actions">
	<a href="<?php echo module('cms')->getUrl('index/restadd'); ?>">添加餐厅</a>
	<a href="<?php echo module('cms')->getUrl('index/restset'); ?>">指定今日餐厅</a>
	<a href="<?php echo module('cms')->getUrl('index/menuadd'); ?>">添加菜单</a>
</div> 
<div class="add-user"><?php //print_r($temp_restinfo); ?>
	<div class="rest-info"> 
		<div class="now-rest"><label>当前餐厅名称:</label><span><?php echo $temp_restinfo['name']; ?>&nbsp;&nbsp;</span></div>
		<div><label>电话:</label><span><?php echo $temp_restinfo['phone']; ?>&nbsp;&nbsp;</span></div>
		<div><label>地址:</label><span><?php echo $temp_restinfo['addr']; ?>&nbsp;&nbsp;</span></div> 
		<div><label>状态:</label>
			<?php if($temp_restinfo['lock'] == 0): ?>
				<span>正常</span>
			<?php else: ?>
				<span>锁定</span>
			<?php endif; ?>
		</div> 
		<br class="clearboth" />
	</div>
	<div class="menus"><?php echo module('admin')->getRestMenu($temp_restinfo['id'],$temp_restinfo['name']);?></div>
	<form action="<?php echo module('cms')->getUrl('admin/menuadd'); ?>" method="post">
		<input type="hidden" name="menurid" value="<?php echo $temp_restinfo['id'];?>" />
		<div><label>套餐名称：</label><input type="text" name="menuname" />  </div>
		<div><label>价格：</label><input type="text" name="menuprice" />   </div>
		<div><label>状态：</label><select type="text" name="menulock">  
			<option value="0" selected><span>正常</span></option>
			<option value="1"><span>锁定</span></option>
		</select>  <br /> </div>
		<div class="sub-action">
		<input type="reset" value="重置" />
		<input type="submit" value="添加" />
		</div>
	</form>
<a class="goback" href="<?php echo module('cms')->getUrl('index/menuadmin'); ?>">返回菜单管理</a>
</div>

{include file="html/footer"}