{include file="html/header"}
<div class="comm-actions">
	<a href="<?php echo module('cms')->getUrl('index/restadd'); ?>">添加餐厅</a>
	<a href="<?php echo module('cms')->getUrl('index/restset'); ?>">指定今日餐厅</a>
	<a href="<?php echo module('cms')->getUrl('index/menuadd'); ?>">添加菜单</a>
</div> 
<div class="add-user"><?php print_r($temp_restinfo); ?>
<form action="<?php echo module('cms')->getUrl('admin/_restedit'); ?>" method="post">
	<input type="hidden" name="restid" value="<?php echo $temp_restinfo['id']; ?>" />
	<div><label>餐厅名称：</label><input type="text" name="restname" value="<?php echo $temp_restinfo['name']; ?>" />  </div>
	<div><label>电话：</label><input type="text" name="restphone" value="<?php echo $temp_restinfo['phone']; ?>" />   </div>
	<div><label>地址：</label><input type="text" name="restaddr" value="<?php echo $temp_restinfo['addr']; ?>" />   </div> 
	<div><label>状态：</label><select type="text" name="restlock">  
	<?php if($temp_restinfo['lock'] == 0): ?>
		<option value="0" selected><span>正常</span></option>
		<option value="1"><span>锁定</span></option>
	<?php else: ?>
		<option value="0"><span>正常</span></option>
		<option value="1" selected><span>锁定</span></option>
	<?php endif; ?>
	</select>  <br /> </div> 
	<div class="sub-action">
	<input type="reset" value="重置" />
	<input type="submit" value="提交" />
	</div>
</form>
<a class="goback" href="<?php echo module('cms')->getUrl('index/menuadmin'); ?>">返回菜单管理</a>
</div>

{include file="html/footer"}