{include file="html/header"}
<div class="comm-actions">
	<a href="<?php echo module('cms')->getUrl('index/restadd'); ?>">添加餐厅</a>
	<a href="<?php echo module('cms')->getUrl('index/restset'); ?>">指定今日餐厅</a>
	<a href="<?php echo module('cms')->getUrl('index/menuadd'); ?>">添加菜单</a>
</div> 
<span class="tip-msg">请在大家开始订餐前指定餐厅，点击'提交'后 两小时内的订单 将失效</span>
<div class="now-rests">
	<span class="title">当前指定餐厅：</span>
	<?php print_r(module('diancan')->getNowRests()); ?>
	<br class="clearboth"/>
</div>
<div class="add-money">
<form action="<?php echo module('cms')->getUrl('admin/restset'); ?>" method="post">
	<?php echo module('admin')->getRestList(); ?> <br class="clearboth"/><hr /><br />
	<input type="reset" value="重置" />
	<input type="submit" value="提交" />
</form>
<a class="goback" href="<?php echo module('cms')->getUrl('index/menuadmin'); ?>">返回菜单管理</a>
</div>


{include file="html/footer"}