{include file="html/header"}
<div class="comm-actions">
	<a href="<?php echo module('cms')->getUrl('index/useradd'); ?>">添加新用户</a>
	<a href="<?php echo module('cms')->getUrl('index/addmoney'); ?>">用户批量充值</a>
</div> 
<div class="add-user">
<form action="<?php echo module('cms')->getUrl('admin/useradd'); ?>" method="post">
	<div><label>用户名：</label><input type="text" name="username" />  </div>
	<div><label>密码：</label><input type="password" name="password" />   </div>
	<div><label>QQ：</label><input type="text" name="userqq" />   </div>
	<div><label>金额：</label><input type="text" name="usermoney" />  </div>
	<div><label>状态：</label><select type="text" name="userlock">  
		<option value="0" selected><span>正常</span></option>
		<option value="1"><span>锁定</span></option>
	</select>  <br /> </div>
	<div><label>角色：</label><select type="text" name="userlevel">
		<option value="0" selected><span>普通用户</span></option>
		<option value="9"><span>管理员</span></option>
	</select>   </div>
	<div class="sub-action">
	<input type="reset" value="重置" />
	<input type="submit" value="添加" />
	</div>
</form>
<a class="goback" href="<?php echo module('cms')->getUrl('index/useradmin'); ?>">返回用户管理</a>
</div>

{include file="html/footer"}